### ISSUE TITLE
Custom menu in site.yaml ignored

### ISSUE THREAD

**Issue by zoof** [OleVik/grav-theme-scholar#17]
I have a site where I've been using `antimatter` for years where I configured custom menu entries in `site.yaml`.  I decided to try `scholar` and everything looks great but the menu entries are wrong.  For example, with Antimatter, I get "Home", "Curriculum Vitae", "Publications", "Working papers" and "Contact" but upon activating `scholar`, there is no longer a "Home" entry and I get "Curriculum Vitae", "Contact" but the menu entries corresponding to the anchors are not present.  Moreover, three additional pages that are "hidden" do show up.  My menu configuration in `site.yaml` given is below.

```
menu:
  -
    text: Publications
    url: 'https://example.com/cv#publications'
  -
    text: 'Working papers'
    url: 'https://example.com/cv#working-papers'
  -
    text: Contact
    url: 'https://example.com/contact'
```
